name: psychopy-leap
channels:
- conda-forge
dependencies:
- python=3.9
- psychopy
- matplotlib=3.3.3
- numpy>=1.19.5
- pandas=1.1.5
- anypytools=1.11.1
- gooey=1.0.8.1
- pywin32=301
- pywinauto=0.6.8
- wxpython>=4.1.0
- pip
- pip:
  - psychtoolbox
  - pygame
  - pyo
  - pyparallel; platform_system != "Windows"
  - SoundFile; platform_system == "Windows"
  - websocket_client